"""
artifact_writer.py
Responsible for saving artifacts generated by the LangGraph pipeline.

Artifacts are stored under:
    pubmed_pipeline/data/artifacts/{trace_id}/
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional


# Root path: pubmed_pipeline/data/artifacts
BASE_DIR = Path(__file__).resolve().parents[2]  # pubmed_pipeline/
ARTIFACT_ROOT = BASE_DIR / "data" / "artifacts"


class ArtifactWriter:
    def __init__(self, trace_id: str):
        self.trace_id = trace_id
        self.dir = ARTIFACT_ROOT / trace_id
        self.dir.mkdir(parents=True, exist_ok=True)

    def write_text(self, filename: str, content: str) -> str:
        path = self.dir / filename
        path.write_text(content or "", encoding="utf-8")
        return str(path)

    def write_json(self, filename: str, data: Any) -> str:
        path = self.dir / filename
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        return str(path)

    def save_all(
        self,
        summary: Optional[str],
        insights: Any,
        retrieved_docs: Any,
        final_answer: Optional[str],
        state: Dict[str, Any],
        metadata: Dict[str, Any],
    ) -> Dict[str, str]:
        """
        Saves all artifacts for a given pipeline run.
        Returns: dict of artifact_name → file_path
        """

        return {
            "summary": self.write_text("summary.txt", summary or ""),
            "insights": self.write_json("insights.json", insights),
            "retrieved_docs": self.write_json("retrieved_docs.json", retrieved_docs),
            "final_answer": self.write_text("final_answer.txt", final_answer or ""),
            "state": self.write_json("state.json", state),
            "metadata": self.write_json("metadata.json", metadata),
        }
